services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: pipolink-backend
    container_name: pipolink-backend
    restart: unless-stopped
    env_file:
      - ./server/.env
    ports:
      - "2654:2654"
    volumes:
      - ./server/storage:/app/storage

