export const WsEventName = {
  AuthInit: "auth.init",
  AuthRefresh: "auth.refresh",
  SyncResume: "sync.resume",
  SystemReady: "system.ready",
  SystemAck: "system.ack",
  SystemError: "system.error",
  SystemPing: "system.ping",
  SystemPong: "system.pong",
  MessageSend: "message.send",
  MessageUpdate: "message.update",
  MessageDelete: "message.delete",
  MessageDelivered: "message.delivered",
  MessageRead: "message.read",
  MessageCreated: "message.created",
  MessageUpdated: "message.updated",
  MessageDeleted: "message.deleted",
  ConversationCreate: "conversation.create",
  ConversationUpdate: "conversation.update",
  ConversationCreated: "conversation.created",
  ConversationUpdated: "conversation.updated",
  NotificationCreated: "notification.created",
  AnnouncementCreated: "announcement.created",
  DocumentUploaded: "document.uploaded",
  DocumentUpdated: "document.updated",
  DeviceLinked: "device.linked",
  DeviceRevoked: "device.revoked",
  SubscriptionUpdated: "subscription.updated",
  AiResponseCreated: "ai.response.created",
  PresenceUpdated: "presence.updated",
  TypingStarted: "typing.started",
  TypingStopped: "typing.stopped",
} as const;

export type WsEventNameType = typeof WsEventName[keyof typeof WsEventName];
