name: Déploiement automatique sur VPS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: 📥 Checkout du code
        uses: actions/checkout@v4

      - name: 🔑 Connexion SSH et déploiement sur le VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEYS }}
          script_stop: true
          script: |
            set -e
            cd ~/Documents/pipolink

            chmod +x deploy.sh
            ./deploy.sh